# Generated by Django 5.1.6 on 2025-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_actor_genre_rename_title_movie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
